### ISSUE TITLE
Publish master instead of gh-pages

### ISSUE THREAD

**Issue by planemad** [RaghavCM/CityIdols#7]
@RaghavCM can you change the Github page source to `master` from the project settings https://github.com/blog/2228-simpler-github-pages-publishing. 

This will allow us to view the work so far live on  https://RaghavCM.github.io/CityIdols/volunteer

**Comment by RaghavCM** [comment]
Dear all,

Sorry for the delay in making the change. I have just made the page source
to master. Please let me know if this is fine.

Thank you so much for your help.

Regards,
Raghav

**Comment by planemad** [comment]
Thank you!
